### ISSUE TITLE
webflux-streaming-demo 

### ISSUE THREAD

**Issue by xiangyang-gao** [ZhongyangMA/webflux-streaming-demo#5]
首先感谢梳理这么完整的文档。

我在阅读中看到图片有些失效。不知是否有时间补一下。
谢谢啦

**Comment by xiangyang-gao** [comment]
<img width="760" alt="demo1" src="https://user-images.githubusercontent.com/15973635/81879161-8f5f5000-95bc-11ea-8d20-471017993569.png">
<img width="834" alt="demo2" src="https://user-images.githubusercontent.com/15973635/81879164-91291380-95bc-11ea-832c-13694312c04a.png">

**Comment by jwf1173** [comment]
同问下图片能补下吗，大大
